name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  check-tag:
    name: Check if version is new
    runs-on: ubuntu-latest
    outputs: 
        releaseExists: ${{ steps.check-tag.outputs.exists }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Project version
        id: get-version
        uses: kzrnm/get-net-sdk-project-versions-action@v1
        with:
          proj-path: FormMatter.OpenGL/FormMatter.OpenGL.csproj

      - uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with: 
          tag: 'v${{ steps.get-version.outputs.package-version }}'

  createRelease:
    runs-on: ubuntu-latest
    name: Create new Release
    needs: check-tag
    if: needs.check-tag.outputs.releaseExists == 'false'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
          
      - name: Install dependencies
        run: dotnet restore

      - name: Add NuGet Source
        run: | 
          dotnet nuget add source --username kris701 --password ${{ secrets.API_KEY_GITHUB }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/kris701/index.json"

      - name: Build (Release) and Publish [FormMatter.Builders]
        run: |  
          cd FormMatter.Builders
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../..

      - name: Build (Release) and Publish [FormMatter.OpenGL]
        run: |  
          cd FormMatter.OpenGL
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../..
          
      - name: Get Package version
        id: get-version
        uses: kzrnm/get-net-sdk-project-versions-action@v1
        with:
          proj-path: FormMatter.OpenGL/FormMatter.OpenGL.csproj

      - name: Generate tag
        continue-on-error: true
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "v${{ steps.get-version.outputs.package-version }}"
          message: "Latest release"

      - name: Generate Release
        uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          artifacts: "*/bin/Release/*.nupkg"
          tag: "v${{ steps.get-version.outputs.package-version }}"

  testBuild:
    runs-on: ubuntu-latest
    name: Build
    needs: check-tag
    if: needs.check-tag.outputs.releaseExists == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore